import mongoose from 'mongoose';
import bcrypt from 'bcryptjs';
import User from '../../backend/src/models/User.js';
import Complaint from '../../backend/src/models/Complaint.js';

const uri = process.env.MONGO_URI;
if (!uri) {
  console.log('MONGO_URI is not set. The app already includes community and duplicate demo records in its in-memory fallback, so no seed is required.');
  process.exit(0);
}

await mongoose.connect(uri);
await Promise.all([User.deleteMany({}), Complaint.deleteMany({})]);

const citizenHash = await bcrypt.hash('citizen123', 10);
const authorityHash = await bcrypt.hash('authority123', 10);
const citizens = await User.insertMany([
  { full_name: 'Demo Citizen', email: 'citizen@civicpulse.demo', password_hash: citizenHash, role: 'citizen' },
  { full_name: 'Neha', email: 'neha@civicpulse.demo', password_hash: citizenHash, role: 'citizen' },
  { full_name: 'Arjun', email: 'arjun@civicpulse.demo', password_hash: citizenHash, role: 'citizen' },
  { full_name: 'Sana', email: 'sana@civicpulse.demo', password_hash: citizenHash, role: 'citizen' },
]);
await User.create({ full_name:'Demo Authority', email:'authority@civicpulse.demo', password_hash:authorityHash, role:'authority', department:'Roads Department' });

const [demo, neha, arjun, sana] = citizens;
const hoursAgo = (h) => new Date(Date.now() - h * 3600000);
const daysAgo = (d) => new Date(Date.now() - d * 86400000);
const complaintRows = [
  { key:'hitec-pothole', user_id:neha.id, reporter_name:'Neha', title:'Large pothole near Cyber Towers', description:'Deep pothole near the junction causing vehicles to swerve.', category:'pothole', severity:'high', priority_score:86, suggested_department:'Roads Department', ai_summary:'Large pothole detected on a busy road and may cause accidents.', photo_url:'/demo-issues/pothole.jpg', status:'in_progress', latitude:17.44850, longitude:78.37420, location_text:'HITEC City, Hyderabad', area:'HITEC City', supporters:[demo.id,'s1','s2','s3','s4','s5'], assigned_to:'Road Repair Team 4', created_at:hoursAgo(2) },
  { key:'madhapur-garbage', user_id:arjun.id, reporter_name:'Arjun', title:'Garbage overflowing beside main road', description:'Garbage bins are full and waste is spreading onto the road.', category:'garbage', severity:'medium', priority_score:67, suggested_department:'Sanitation & Waste Management', ai_summary:'Accumulated garbage beside a busy road requires municipal cleanup.', photo_url:'/demo-issues/garbage.jpg', status:'assigned', latitude:17.44590, longitude:78.37710, location_text:'Madhapur, Hyderabad', area:'Madhapur', supporters:['s6','s7','s8'], assigned_to:'Sanitation Team 2', created_at:hoursAgo(8) },
  { key:'hitec-wire', user_id:sana.id, reporter_name:'Sana', title:'Loose electric wire near school gate', description:'The electric wire is hanging very low near the school entrance.', category:'loose_electric_wire', severity:'critical', priority_score:97, suggested_department:'Electricity Department', ai_summary:'Low-hanging electric wire near a sensitive area creates an electrocution risk.', photo_url:'/demo-issues/loose-electric-wire.jpg', status:'verified', latitude:17.45020, longitude:78.37290, location_text:'HITEC City, Hyderabad', area:'HITEC City', supporters:['a','b','c','d','e','f','g','h','i','j','k'], created_at:hoursAgo(5) },
  { key:'balanagar-main', user_id:arjun.id, reporter_name:'Arjun', title:'Deep pothole near Balanagar Metro gate', description:'A wide pothole has formed beside the metro approach road.', category:'pothole', severity:'high', priority_score:82, suggested_department:'Roads Department', ai_summary:'Large road pothole close to the metro entrance may endanger two-wheelers.', photo_url:'/demo-issues/pothole.jpg', status:'assigned', latitude:17.47672, longitude:78.44816, location_text:'Balanagar Metro, Hyderabad', area:'Balanagar', supporters:['u1','u2','u3','u4','u5','u6','u7','u8'], assigned_to:'Road Repair Team 2', created_at:hoursAgo(4) },
  { key:'balanagar-duplicate', user_id:sana.id, reporter_name:'Sana', title:'Pothole beside Balanagar Metro entrance', description:'There is a large pothole very close to the metro gate on the service lane.', category:'pothole', severity:'high', priority_score:74, suggested_department:'Roads Department', ai_summary:'Possible duplicate pothole report close to an existing Balanagar road complaint.', photo_url:'/demo-issues/pothole.jpg', status:'reported', latitude:17.47690, longitude:78.44829, location_text:'Balanagar Metro, Hyderabad', area:'Balanagar', supporters:['u9','u10'], created_at:hoursAgo(1.5) },
  { key:'ameerpet-light', user_id:demo.id, reporter_name:'Demo Citizen', title:'Streetlight not working', description:'The streetlight has not worked for three nights and the lane is very dark.', category:'broken_streetlight', severity:'medium', priority_score:58, suggested_department:'Electricity Department', ai_summary:'Non-functional streetlight is reducing nighttime visibility in a residential lane.', photo_url:'/demo-issues/broken-streetlight.jpg', status:'verified', latitude:17.43758, longitude:78.44829, location_text:'Ameerpet, Hyderabad', area:'Ameerpet', supporters:['m1','m2','m3','m4'], created_at:hoursAgo(13) },
  { key:'kukatpally-water', user_id:arjun.id, reporter_name:'Arjun', title:'Water leakage on main street', description:'Clean water has been leaking continuously from a damaged pipe.', category:'water_leakage', severity:'high', priority_score:79, suggested_department:'Water Works Department', ai_summary:'Continuous pipeline leakage is wasting water and making the road slippery.', photo_url:'/demo-issues/water-leakage.jpg', status:'in_progress', latitude:17.49320, longitude:78.39910, location_text:'Kukatpally, Hyderabad', area:'Kukatpally', supporters:['w1','w2','w3','w4','w5','w6'], assigned_to:'Water Works Team 1', created_at:hoursAgo(10) },
  { key:'secunderabad-manhole', user_id:sana.id, reporter_name:'Sana', title:'Open manhole near bus stop', description:'The manhole cover is missing near the bus stop and is dangerous at night.', category:'open_manhole', severity:'critical', priority_score:94, suggested_department:'Drainage & Sewerage', ai_summary:'Open manhole in a pedestrian area presents an immediate fall and traffic hazard.', photo_url:'/demo-issues/open-manhole.jpg', status:'reported', latitude:17.43990, longitude:78.49830, location_text:'Secunderabad, Hyderabad', area:'Secunderabad', supporters:['s1','s2','s3','s4','s5','s6','s7','s8','s9'], created_at:hoursAgo(0.75) },
  { key:'madhapur-drain', user_id:neha.id, reporter_name:'Neha', title:'Drainage water overflowing', description:'Drainage water is overflowing after rain and blocking one side of the lane.', category:'drainage', severity:'high', priority_score:76, suggested_department:'Drainage & Sewerage', ai_summary:'Overflowing drainage is creating sanitation and access problems for nearby residents.', photo_url:'/demo-issues/drainage.jpg', status:'verified', latitude:17.44420, longitude:78.37630, location_text:'Madhapur, Hyderabad', area:'Madhapur', supporters:['d1','d2','d3','d4','d5'], created_at:hoursAgo(6) },
  { key:'moosapet-road', user_id:arjun.id, reporter_name:'Arjun', title:'Damaged road surface near market', description:'A long section of the road surface is broken and uneven near the market.', category:'damaged_road', severity:'medium', priority_score:64, suggested_department:'Roads Department', ai_summary:'Uneven damaged road surface needs resurfacing before the condition worsens.', photo_url:'/demo-issues/damaged-road.jpg', status:'resolved', latitude:17.48410, longitude:78.41370, location_text:'Moosapet, Hyderabad', area:'Moosapet', supporters:['r1','r2'], assigned_to:'Road Repair Team 1', created_at:hoursAgo(72) },,
  { key:'balanagar-drain', user_id:neha.id, reporter_name:'Neha', title:'Open drainage channel beside school road', description:'An uncovered drain with stagnant wastewater is open beside the footpath.', category:'drainage', severity:'high', priority_score:88, suggested_department:'Drainage & Sewerage', ai_summary:'Open drainage with stagnant water creates sanitation and pedestrian safety risks.', photo_url:'/demo-issues/drainage.jpg', status:'reported', latitude:17.47610, longitude:78.44772, location_text:'Balanagar, Hyderabad', area:'Balanagar', supporters:['hb1','hb2','hb3','hb4','hb5','hb6','hb7'], created_at:daysAgo(9) },
  { key:'balanagar-garbage', user_id:arjun.id, reporter_name:'Arjun', title:'Garbage pile blocking service lane', description:'Mixed garbage has accumulated beside the service road and has not been cleared.', category:'garbage', severity:'medium', priority_score:73, suggested_department:'Sanitation & Waste Management', ai_summary:'Garbage accumulation is obstructing the lane and attracting stray animals.', photo_url:'/demo-issues/garbage.jpg', status:'reported', latitude:17.47725, longitude:78.44791, location_text:'Balanagar, Hyderabad', area:'Balanagar', supporters:['gb1','gb2','gb3','gb4'], created_at:daysAgo(7) },
  { key:'balanagar-wire', user_id:sana.id, reporter_name:'Sana', title:'Loose electric cable near market', description:'A live-looking cable is hanging low above the roadside shops.', category:'loose_electric_wire', severity:'critical', priority_score:98, suggested_department:'Electricity Department', ai_summary:'Low-hanging electrical cable in a crowded market area requires urgent inspection.', photo_url:'/demo-issues/loose-electric-wire.jpg', status:'verified', latitude:17.47598, longitude:78.44880, location_text:'Balanagar, Hyderabad', area:'Balanagar', supporters:['eb1','eb2','eb3','eb4','eb5','eb6','eb7','eb8','eb9'], created_at:daysAgo(3) },
  { key:'balanagar-water', user_id:demo.id, reporter_name:'Demo Citizen', title:'Water pipeline leaking near metro road', description:'A damaged municipal pipe is continuously leaking water onto the road.', category:'water_leakage', severity:'high', priority_score:85, suggested_department:'Water Works Department', ai_summary:'Continuous water leakage is wasting water and weakening the road surface.', photo_url:'/demo-issues/water-leakage.jpg', status:'assigned', latitude:17.47745, longitude:78.44862, location_text:'Balanagar, Hyderabad', area:'Balanagar', supporters:['wb1','wb2','wb3','wb4','wb5'], assigned_to:'Water Works Team 3', created_at:daysAgo(5) },
  { key:'balanagar-light', user_id:neha.id, reporter_name:'Neha', title:'Streetlights dark for several nights', description:'Two streetlights near the bus stop are not working after sunset.', category:'broken_streetlight', severity:'medium', priority_score:69, suggested_department:'Electricity Department', ai_summary:'Repeated streetlight failure is reducing night visibility around a transit stop.', photo_url:'/demo-issues/broken-streetlight.jpg', status:'reported', latitude:17.47654, longitude:78.44905, location_text:'Balanagar, Hyderabad', area:'Balanagar', supporters:['lb1','lb2','lb3'], created_at:daysAgo(11) },
  { key:'balanagar-road', user_id:arjun.id, reporter_name:'Arjun', title:'Road surface broken near industrial gate', description:'The road surface has cracked and sunk across a large patch.', category:'damaged_road', severity:'high', priority_score:81, suggested_department:'Roads Department', ai_summary:'Damaged road surface is worsening under heavy vehicle traffic.', photo_url:'/demo-issues/damaged-road.jpg', status:'verified', latitude:17.47565, longitude:78.44745, location_text:'Balanagar, Hyderabad', area:'Balanagar', supporters:['rb1','rb2','rb3','rb4','rb5','rb6'], created_at:daysAgo(8) },
  { key:'balanagar-manhole', user_id:sana.id, reporter_name:'Sana', title:'Open manhole near pedestrian crossing', description:'The manhole lid is missing close to a busy crossing.', category:'open_manhole', severity:'critical', priority_score:96, suggested_department:'Drainage & Sewerage', ai_summary:'Open manhole creates an immediate fall hazard for pedestrians and riders.', photo_url:'/demo-issues/open-manhole.jpg', status:'reported', latitude:17.47702, longitude:78.44934, location_text:'Balanagar, Hyderabad', area:'Balanagar', supporters:['mb1','mb2','mb3','mb4','mb5','mb6','mb7','mb8'], created_at:daysAgo(10) },
  { key:'kukatpally-pothole', user_id:neha.id, reporter_name:'Neha', title:'Potholes near Kukatpally junction', description:'Several potholes have formed along the junction approach.', category:'pothole', severity:'high', priority_score:83, suggested_department:'Roads Department', ai_summary:'Multiple potholes are affecting traffic movement near a busy junction.', photo_url:'/demo-issues/pothole.jpg', status:'reported', latitude:17.49362, longitude:78.39862, location_text:'Kukatpally, Hyderabad', area:'Kukatpally', supporters:['kp1','kp2','kp3','kp4','kp5'], created_at:daysAgo(4) },
  { key:'kukatpally-drain', user_id:sana.id, reporter_name:'Sana', title:'Drain overflow after rain', description:'A blocked drain is overflowing and spreading dirty water across the lane.', category:'drainage', severity:'high', priority_score:84, suggested_department:'Drainage & Sewerage', ai_summary:'Blocked drainage is causing wastewater overflow after rainfall.', photo_url:'/demo-issues/drainage.jpg', status:'verified', latitude:17.49305, longitude:78.40012, location_text:'Kukatpally, Hyderabad', area:'Kukatpally', supporters:['kd1','kd2','kd3','kd4','kd5'], created_at:daysAgo(6) },
  { key:'madhapur-open-drain', user_id:demo.id, reporter_name:'Demo Citizen', title:'Open drain beside tech park lane', description:'The roadside drain is uncovered and partially blocked by debris.', category:'drainage', severity:'high', priority_score:82, suggested_department:'Drainage & Sewerage', ai_summary:'Uncovered drainage beside a high-footfall lane presents safety and sanitation risks.', photo_url:'/demo-issues/drainage.jpg', status:'reported', latitude:17.44685, longitude:78.37552, location_text:'Madhapur, Hyderabad', area:'Madhapur', supporters:['md1','md2','md3','md4'], created_at:daysAgo(4) },
  { key:'madhapur-manhole', user_id:sana.id, reporter_name:'Sana', title:'Open manhole on service road', description:'A manhole cover is displaced on the service road near offices.', category:'open_manhole', severity:'critical', priority_score:93, suggested_department:'Drainage & Sewerage', ai_summary:'Displaced manhole cover creates a serious traffic and pedestrian hazard.', photo_url:'/demo-issues/open-manhole.jpg', status:'in_progress', latitude:17.44642, longitude:78.37708, location_text:'Madhapur, Hyderabad', area:'Madhapur', supporters:['mm1','mm2','mm3','mm4','mm5','mm6'], assigned_to:'Drainage Emergency Team 1', created_at:daysAgo(2) }
];

const created = {};
for (const row of complaintRows) {
  const { key, ...doc } = row;
  created[key] = await Complaint.create(doc);
}
created['balanagar-duplicate'].duplicate_of = created['balanagar-main'].id;
await created['balanagar-duplicate'].save();

console.log(`MongoDB demo data seeded: ${Object.keys(created).length} community complaints, including a Balanagar duplicate pair.`);
await mongoose.disconnect();
